---
- name: Налаштування мережевого захисту (UFW)
  hosts: my_computers
  become: yes               # Нам потрібні права "root", бо ми міняємо системний фаєрвол

  tasks:
    - name: Встановити утиліту UFW
      apt:
        name: ufw
        state: present      # Перевіряємо, щоб програма була встановлена

    - name: Дозволити SSH (Порт 22)
      ufw:
        rule: allow         # Наказ: "Пропускати"
        port: '22'          # Номер "дверей" для SSH
        proto: tcp          # Протокол надійної передачі даних

    - name: Дозволити HTTP (Порт 80)
      ufw:
        rule: allow
        port: '80'          # Номер "дверей" для веб-сайтів
        proto: tcp

    - name: Увімкнути фаєрвол та закрити все інше
      ufw:
        state: enabled      # Вмикаємо "охорону"
        policy: deny        # Правило: "Все, що не дозволено явно — ЗАБОРОНЕНО"
        direction: incoming # Стосується тільки вхідних запитів з інтернету
