---
- name: Звіт про стан моєї системи
  hosts: my_computers
  become: yes               # Права адміна потрібні, щоб зазирнути в системні логи

  tasks:
    - name: Перевірити вільну оперативну пам'ять (RAM)
      shell: "free -m"      # Команда покаже пам'ять у Мегабайтах
      register: ram_result  # Зберігаємо результат у "коробочку" (змінну)

    - name: Перевірити місце на диску
      shell: "df -h /"      # -h робить цифри зрозумілими (Gb, Mb)
      register: disk_result

    - name: Перевірити, чи бачить комп'ютер інтернет
      shell: "ping -4 -c 3 google.com" # Пінгуємо 3 рази. Додали -4 для IPv4
      register: ping_result
      ignore_errors: yes

    - name: ВИВЕСТИ ЗВІТ НА ЕКРАН
      debug:                # Спеціальний модуль для друку результатів
        msg: 
          - "--- ОПЕРАТИВКА (дивись колонку free) ---"
          - "{{ ram_result.stdout }}"
          - "--- ДИСК (дивись колонку Avail) ---"
          - "{{ disk_result.stdout }}"
          - "--- ІНТЕРНЕТ (якщо 0% packet loss — все ок) ---"
          - "{{ ping_result.stdout_lines[1] }}" # Виведемо тільки один рядок для чистоти
